# Generated by Django 4.2.2 on 2023-08-17 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_likes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Likes',
            new_name='Like',
        ),
    ]
